name: "CI"
on: ["push", "pull_request"]

jobs:
  lint:
    name: "Run static analysis"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: "1.14.x"
    - run: "GO111MODULE=on go get honnef.co/go/tools/cmd/staticcheck@sarif"
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/cache@v2
      with:
        path: ~/.cache/staticcheck
        key: staticcheck-${{ github.sha }}
        restore-keys: |
          staticcheck-
    - run: "go vet ./..."
    - run: "$(go env GOPATH)/bin/staticcheck -go 1.14 -f sarif ./... >results.sarif"
    - uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif
