on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  foo:
    name: some job
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: WillAbides/setup-go-faster@v1.5.0
        with:
          go-version: "1.16.x"
          ignore-local: true
      - id: foo
        run: "echo $PATH"
        shell: bash
      - run: "$Env:Path"
      # - run: "go version"
      # - name: Run Staticcheck
      #   uses: dominikh/staticcheck-action@master
      # - run: "go version"
