on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  foo:
    name: some job
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: WillAbides/setup-go-faster@v1.5.0
        with:
          go-version: "1.13.x"
      - name: Run Staticcheck
        uses: dominikh/staticcheck-action@70e01c2cc985435d6ddecd8f8258f6d572e3d739
        with:
          install-go: false
